import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import QRCode from "qrcode";
import { useState } from "react";
export default function Home() {
  const [qrcode, setQrCode] = useState("");
  const [link, setLink] = useState("");
  const [size, setSize] = useState("");
  const handleSelect = (e) => {
    setSize(e.target.value);
  };
  const getQRCode = (e) => {
    e.preventDefault();
    QRCode.toDataURL(
      link,
      {
        width: size,
        heigt: size,
        margin: 2,
      },
      (err, url) => {
        if (err) return console.error(err);
        console.log(url);
        setQrCode(url);
      }
    );
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <select onChange={handleSelect}>
          <option value="100">100x100</option>
          <option value="200">200x200</option>
          <option value="300">300x300</option>
          <option value="400">400x400</option>
          <option value="500">500x500</option>
          <option value="600">600x600</option>
          <option value="700">700x700</option>
          <option value="800">800x800</option>
          <option value="900">900x900</option>
        </select>
        <form className={styles.form}>
          <div className={styles.inputwrapper}>
            <input
              value={link}
              onChange={(evt) => setLink(evt.target.value)}
              placeholder="Link"
              className={styles.formInput}
            />
            <label className={styles.formLabel}>Link</label>
          </div>
          <button onClick={getQRCode}>Generate</button>
        </form>
        {qrcode && (
          <>
            <img src={qrcode} />
          </>
        )}{" "}
      </main>
    </div>
  );
}
