import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import QRCode from "qrcode";
import { useState } from "react";
export default function Home() {
  const [qrcode, setQrCode] = useState("");
  const [link, setLink] = useState("https://");
  const [size, setSize] = useState("");
  const handleSelect = (e) => {
    setSize(e.target.value);
  };
  const getQRCode = (e) => {
    e.preventDefault();
    QRCode.toDataURL(
      link,
      {
        width: size,
        heigt: size,
        margin: 2,
      },
      (err, url) => {
        if (err) return console.error(err);
        console.log(url);
        setQrCode(url);
      }
    );
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="w-full text-center p-4 bg-red-300">
        <h1>Hello</h1>
      </header>
      <main className="pt-6 w-1/2 h-screen m-auto bg-gray-200">
        <div className="w-full flex justify-around items-center pt-4 pb-4">
          <select onChange={handleSelect} className="p-2">
            <option value="100">100x100</option>
            <option value="200">200x200</option>
            <option value="300">300x300</option>
            <option value="400">400x400</option>
            <option value="500">500x500</option>
            <option value="600">600x600</option>
            <option value="700">700x700</option>
            <option value="800">800x800</option>
            <option value="900">900x900</option>
          </select>
          <form className=" flex items-center">
            <div className="pr-4">
              <input
                value={link}
                type="text"
                onChange={(evt) => setLink(evt.target.value)}
                placeholder="Link"
                className={styles.formInput}
              />
              <label className={styles.formLabel}>Link</label>
            </div>
            <button onClick={getQRCode}>Generate</button>
          </form>
        </div>
        {qrcode && (
          <div className="w-full flex justify-center">
            <img src={qrcode} className="p-2 bg-gray-400" />
          </div>
        )}{" "}
      </main>
    </div>
  );
}
